apiVersion: v1
kind: Service
metadata:
  name: order-internal
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: order
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    # 멀티 포트
    - name: actuator
      port: 8081
      targetPort: actuator
      protocol: TCP
  trafficDistribution: PreferClose
---
apiVersion: v1
kind: Service
metadata:
  name: order-public
  namespace: production
spec:
  type: NodePort
  selector:
    app: order
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31200
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: external-mysql
  namespace: production
spec:
  clusterIP: None
  type: ExternalName
  externalName: www.google.com
  # ExternalName은 selector, ports 필요 없음